// <auto-generated />
using Duyen158.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duyen158.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002055547_Create_Table_Person")]
    partial class Create_Table_Person
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Duyen158.Models.Person", b =>
                {
                    b.Property<string>("CanCuocCongDan")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CanCuocCongDan");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
